// Walk-by barks: one-liners called out unprompted. Translations live in barks-i18n.json.
export const BARKS = [
  { who: 'any', text: "Mind the sheep. Wait, those are clouds. Mind the clouds.", when: {} },
  { who: 'any', text: "I came out for something and forgot it. Nice walk, though.", when: {} },
  { who: 'man', text: "Somebody borrowed my ladder in March. I'm not counting.", when: {} },
  { who: 'woman', text: "My knees say hello. The rest of me is busy.", when: {} },
  { who: 'any', text: "Careful on the planks, they have opinions.", when: {} },
  { who: 'any', text: "If you smell bread, follow it. That's just good sense.", when: {} },
  { who: 'man', text: "The valley is small, but it keeps its secrets well.", when: {} },
  { who: 'woman', text: "Lost a glove. It's probably off with the odd sock.", when: {} },
  { who: 'any', text: "A good walk is better than a bad nap.", when: {} },
  { who: 'any', text: "Have you seen my hat? Oh. It's on my head.", when: {} },
  { who: 'man', text: "I'm not lost. I'm taking the scenic route.", when: {} },
  { who: 'woman', text: "Thirty years here and I still mix up the lanes.", when: {} },
  { who: 'any', text: "Somebody left a kite in my pear tree.", when: {} },
  { who: 'any', text: "The chickens are in charge today. I just work here.", when: {} },
  { who: 'man', text: "Tea first, chores second. That's the valley way.", when: {} },
  { who: 'woman', text: "Every path leads somewhere. Some just take longer.", when: {} },
  { who: 'any', text: "I counted the stars once. I kept falling asleep.", when: {} },
  { who: 'any', text: "My neighbour's rooster has no sense of time.", when: {} },
  { who: 'man', text: "Watch your step. The cat owns the road.", when: {} },
  { who: 'woman', text: "I'd wave, but my hands are full of turnips.", when: {} },
  { who: 'any', text: "A little walk, a little gossip. That's a whole day.", when: {} },
  { who: 'any', text: "Is it Tuesday? It feels like a Tuesday.", when: {} },
  { who: 'man', text: "Some days the valley hums. Today I think it's humming.", when: {} },
  { who: 'woman', text: "I keep meaning to fix that fence. Keep meaning to.", when: {} },
  { who: 'any', text: "Bicycles are fast. Feet are honest.", when: {} },
  { who: 'any', text: "Two buttons missing and nobody noticed. A victory.", when: {} },
  { who: 'man', text: "Fresh air, full pockets, nowhere to be. Perfect.", when: {} },
  { who: 'woman', text: "I know every stone on this road by its first name.", when: {} },
  { who: 'any', text: "The wind carries every secret, but only tells the birds.", when: {} },
  { who: 'any', text: "Soup's on! Well, it's on my mind.", when: {} },
  { who: 'man', text: "Nobody here is in a hurry, and we're proud of it.", when: {} },
  { who: 'woman', text: "Look up! The sky is showing off tonight.", when: {night:true} },
  { who: 'any', text: "Shh, the lamps are listening.", when: {night:true} },
  { who: 'any', text: "I should be in bed. The stars said otherwise.", when: {night:true} },
  { who: 'man', text: "Careful in the dark. Roots love a late stroll.", when: {night:true} },
  { who: 'woman', text: "Owls are out. I'm just their clumsy neighbour.", when: {night:true} },
  { who: 'any', text: "Can't sleep. I'm counting windows instead of sheep.", when: {night:true} },
  { who: 'any', text: "The valley sounds different at night. Softer.", when: {night:true} },
  { who: 'man', text: "Mind the lantern, it's the only one I've got.", when: {night:true} },
  { who: 'woman', text: "Even the river sounds sleepy tonight.", when: {night:true} },
  { who: 'any', text: "A night walk clears the head. And fogs the glasses.", when: {night:true} },
  { who: 'any', text: "Was that a falling star, or just my eyes?", when: {night:true} },
  { who: 'man', text: "Bed is warm, but the night is wider.", when: {night:true} },
  { who: 'woman', text: "Quiet out, isn't it? I could hear a bun cool.", when: {night:true} },
  { who: 'any', text: "Every window up the hill is a tiny moon.", when: {night:true} },
  { who: 'any', text: "Night shift! I'm guarding the pie. From myself.", when: {night:true} },
  { who: 'man', text: "The dark is friendly here. Mostly.", when: {night:true} },
  { who: 'woman', text: "Late for a stroll, early for a snack.", when: {night:true} },
  { who: 'any', text: "Somewhere, somebody's kettle is still singing.", when: {night:true} },
  { who: 'any', text: "I'm not wandering. I'm night-gardening.", when: {night:true} },
  { who: 'man', text: "Stars out already? I swear it was lunchtime a minute ago.", when: {night:true} },
  { who: 'woman', text: "Up with the day, and the day is up with me.", when: {night:false} },
  { who: 'any', text: "The shadows are short, so it must be lunchtime.", when: {night:false} },
  { who: 'any', text: "Plenty of daylight left. Plenty of chores, too.", when: {night:false} },
  { who: 'man', text: "Off to market with nothing to sell. Moral support.", when: {night:false} },
  { who: 'woman', text: "Sunday hat on a Wednesday. Why not?", when: {night:false} },
  { who: 'any', text: "Birds are loud today. I think it's about breakfast.", when: {night:false} },
  { who: 'any', text: "Daylight's free. I'm spending it on a nap.", when: {night:false} },
  { who: 'man', text: "Kettle's on. That's a proper day.", when: {night:false} },
  { who: 'woman', text: "Chores before lunch, lunch before chores. Balance.", when: {night:false} },
  { who: 'any', text: "Lunch smells are floating over every roof.", when: {night:false} },
  { who: 'any', text: "Good day! I'm out checking on nothing in particular.", when: {night:false} },
  { who: 'man', text: "I took the long way. The short way had a goose.", when: {night:false} },
  { who: 'woman', text: "Nice scarf! Did somebody knit it for you?", when: {} },
  { who: 'any', text: "A tea stain on my sleeve. Medals of honour.", when: {} },
  { who: 'any', text: "Blossom's out! Everything's pink and slightly sneezy.", when: {season:'spring'} },
  { who: 'man', text: "Mud, mud, mud. Spring has arrived on my boots.", when: {season:'spring'} },
  { who: 'woman', text: "Kites are up! Mind the strings.", when: {season:'spring'} },
  { who: 'any', text: "Lambs! Everywhere! I've stopped being useful.", when: {season:'spring'} },
  { who: 'any', text: "Window's open for the first time since autumn.", when: {season:'spring'} },
  { who: 'man', text: "Birds are nesting in my chimney. No fires for me.", when: {season:'spring'} },
  { who: 'woman', text: "Peach buds are fat as thumbs. Soon, soon.", when: {season:'spring'} },
  { who: 'any', text: "The air smells of green. Doesn't it?", when: {season:'spring'} },
  { who: 'any', text: "Spring cleaning. Found a sock from last year.", when: {season:'spring'} },
  { who: 'man', text: "Every puddle has a sky in it. I keep stepping in.", when: {season:'spring'} },
  { who: 'woman', text: "Hot! Even the shade is sweating.", when: {season:'summer'} },
  { who: 'any', text: "Cicadas are shouting. I can't hear my own thoughts.", when: {season:'summer'} },
  { who: 'any', text: "Cold barley tea, a fan, a shady step. Bliss.", when: {season:'summer'} },
  { who: 'man', text: "Long days, short tempers, cold melon. Summer.", when: {season:'summer'} },
  { who: 'woman', text: "The river's the only sensible place today.", when: {season:'summer'} },
  { who: 'any', text: "Hats are a must. The sun here has opinions.", when: {season:'summer'} },
  { who: 'any', text: "Fireflies tonight, I bet. Summer's best trick.", when: {season:'summer'} },
  { who: 'man', text: "Shaved ice, fine as snow. Worth every coin.", when: {season:'summer'} },
  { who: 'woman', text: "I dozed under a tree. Woke with a butterfly on my nose.", when: {season:'summer'} },
  { who: 'any', text: "Sunflowers look up. I try, but my neck is tired.", when: {season:'summer'} },
  { who: 'any', text: "Leaves everywhere. I sweep, they cheerfully return.", when: {season:'autumn'} },
  { who: 'man', text: "Chestnuts! Roasted, they taste like a warm hug.", when: {season:'autumn'} },
  { who: 'woman', text: "Harvest time. My back says no, my pantry says yes.", when: {season:'autumn'} },
  { who: 'any', text: "Smell the woodsmoke? That's autumn knocking.", when: {season:'autumn'} },
  { who: 'any', text: "Red leaves, gold leaves. The hills are showing off.", when: {season:'autumn'} },
  { who: 'man', text: "A pumpkin on every porch. Friendly fellows.", when: {season:'autumn'} },
  { who: 'woman', text: "Shorter days, longer sweaters. I approve.", when: {season:'autumn'} },
  { who: 'any', text: "The wind has a bite in it. A small, friendly bite.", when: {season:'autumn'} },
  { who: 'any', text: "Dragonflies on the water. The last of the summer crowd.", when: {season:'autumn'} },
  { who: 'man', text: "Mushrooms! If you don't know them, don't eat them.", when: {season:'autumn'} },
  { who: 'woman', text: "Brr! My nose is an icicle.", when: {season:'winter'} },
  { who: 'any', text: "Chimney smoke, warm soup, quiet lanes. Cosy winter.", when: {season:'winter'} },
  { who: 'any', text: "Frost on every fence post. Like sugar.", when: {season:'winter'} },
  { who: 'man', text: "Short days. I'm already waiting for supper.", when: {season:'winter'} },
  { who: 'woman', text: "Put on another scarf. Then another.", when: {season:'winter'} },
  { who: 'any', text: "Hot tea for the hands, hot stew for the belly.", when: {season:'winter'} },
  { who: 'any', text: "Winter nights are long. Good for stories.", when: {season:'winter'} },
  { who: 'man', text: "Icicles on the eaves. Don't stand under them, dear.", when: {season:'winter'} },
  { who: 'woman', text: "Breath clouds! Look, I'm a dragon.", when: {season:'winter'} },
  { who: 'any', text: "A blanket and a stove. Don't bother me till spring.", when: {season:'winter'} },
  { who: 'any', text: "Snow! Quick, before it melts!", when: {weather:'snow'} },
  { who: 'man', text: "Snow's piling up. Good thing I like shovels.", when: {weather:'snow'} },
  { who: 'woman', text: "Every roof is wearing a white hat.", when: {weather:'snow'} },
  { who: 'any', text: "Crunch, crunch. Listen to those boots.", when: {weather:'snow'} },
  { who: 'any', text: "Snowfall is so quiet you can hear your thoughts.", when: {weather:'snow'} },
  { who: 'man', text: "A snowman by the gate. He's guarding the lane.", when: {weather:'snow'} },
  { who: 'woman', text: "Nothing like snow to find the holes in your gloves.", when: {weather:'snow'} },
  { who: 'any', text: "Snow on the hills, soup on the stove. Happy.", when: {weather:'snow'} },
  { who: 'any', text: "Mind Mochi! He's asleep in the middle of the road.", when: {place:'kawabe'} },
  { who: 'man', text: "The river's in a talkative mood today.", when: {place:'kawabe'} },
  { who: 'woman', text: "Kawabe folk never hurry. The river doesn't either.", when: {place:'kawabe'} },
  { who: 'any', text: "That's the boathouse. It smells of tar and good stories.", when: {place:'kawabe'} },
  { who: 'any', text: "The ferry leaves when it leaves. That's the schedule.", when: {place:'kawabe'} },
  { who: 'man', text: "Wooden bridge, wooden houses, wooden jokes.", when: {place:'kawabe'} },
  { who: 'woman', text: "Fish for lunch again. The river provides.", when: {place:'kawabe'} },
  { who: 'any', text: "Wash day by the water, same as always.", when: {place:'kawabe'} },
  { who: 'any', text: "Hear the mill wheel? That's Kawabe's heartbeat.", when: {place:'kawabe'} },
  { who: 'man', text: "Everything in Kawabe smells of rope and river.", when: {place:'kawabe'} },
  { who: 'woman', text: "Nets drying, kettles singing. That's Kawabe.", when: {place:'kawabe'} },
  { who: 'any', text: "Takamori folk say we're damp. We say we're fresh.", when: {place:'kawabe'} },
  { who: 'any', text: "Thirty-nine steps to the bell tower. I count every one.", when: {place:'takamori'} },
  { who: 'man', text: "The bakery makes the whole hill smell like heaven.", when: {place:'takamori'} },
  { who: 'woman', text: "Takamori is all stairs. Strong legs, or no dinner.", when: {place:'takamori'} },
  { who: 'any', text: "Our bell rings the hours, when it feels like it.", when: {place:'takamori'} },
  { who: 'any', text: "The view from up here? Kawabe looks like a toy village.", when: {place:'takamori'} },
  { who: 'man', text: "Bicycles rattle on these cobbles. You'll hear them coming.", when: {place:'takamori'} },
  { who: 'woman', text: "Hill air! Good for lungs, bad for hats.", when: {place:'takamori'} },
  { who: 'any', text: "The hill keeps us fit and the bakery keeps us round.", when: {place:'takamori'} },
  { who: 'any', text: "Takamori smells of yeast. Best alarm clock there is.", when: {place:'takamori'} },
  { who: 'man', text: "From the tower you can see the whole valley, and my aunt.", when: {place:'takamori'} },
  { who: 'woman', text: "The wind up here steals hats. The tower has a dozen.", when: {place:'takamori'} },
  { who: 'any', text: "Kawabe folk say we're snooty. We say we're high up.", when: {place:'takamori'} },
  { who: 'any', text: "Hoshi Station: where the valley says hello and goodbye.", when: {place:'hoshi'} },
  { who: 'man', text: "Benches, bells and weeds. Hoshi has it all.", when: {place:'hoshi'} },
  { who: 'woman', text: "The platform gets swept every day. Just in case.", when: {place:'hoshi'} },
  { who: 'any', text: "The sign says Hoshi. I say home.", when: {place:'hoshi'} },
  { who: 'any', text: "The rails run through the valley like a long sentence.", when: {place:'hoshi'} },
  { who: 'man', text: "That little cottage on the hill has stood a long time.", when: {place:'hoshi'} },
  { who: 'woman', text: "Stars come out early at Hoshi. They know this place.", when: {place:'hoshi'} },
  { who: 'any', text: "Smell that? Coal, tea and old wood. That's Hoshi.", when: {place:'hoshi'} },
  { who: 'any', text: "Peach trees, row on row. I know every one.", when: {place:'orchard'} },
  { who: 'man', text: "A ladder, a basket, a bee. That's orchard work.", when: {place:'orchard'} },
  { who: 'woman', text: "Mind the roots. They run all the way to the river.", when: {place:'orchard'} },
  { who: 'any', text: "Pruning is a conversation with the tree. Mine argues.", when: {place:'orchard'} },
  { who: 'any', text: "Every tree here has a name. Mine are all Peach.", when: {place:'orchard'} },
  { who: 'man', text: "The orchard hums. It's the bees, or maybe the trees.", when: {place:'orchard'} },
  { who: 'woman', text: "The hill smells sweet even when nothing's ripe.", when: {place:'orchard'} },
  { who: 'any', text: "Peach trees are patient. They'd like you to be, too.", when: {place:'orchard'} },
  { who: 'any', text: "Row by row, tree by tree. That's how orchards grow.", when: {place:'orchard'} },
  { who: 'man', text: "Quiet, please. The forest is thinking.", when: {place:'shrine'} },
  { who: 'woman', text: "The shrine steps are old. So are my knees.", when: {place:'shrine'} },
  { who: 'any', text: "Moss on every stone. The forest keeps its own time.", when: {place:'shrine'} },
  { who: 'any', text: "Bow, clap, make a wish. Small wishes count most.", when: {place:'shrine'} },
  { who: 'man', text: "Something rustles in the trees. Probably friendly.", when: {place:'shrine'} },
  { who: 'woman', text: "Tall cedars and a quiet hill. Good for the soul.", when: {place:'shrine'} },
  { who: 'any', text: "Lanterns in the moss. Someone cares for this place.", when: {place:'shrine'} },
  { who: 'any', text: "Tread softly. Up here, even the wind whispers.", when: {place:'shrine'} },
  { who: 'man', text: "Splash! Nothing to see. Just a fish with ambition.", when: {place:'river'} },
  { who: 'woman', text: "The ferry rope sings when it's pulled. Listen.", when: {place:'river'} },
  { who: 'any', text: "The ducks think the river's theirs. We let them.", when: {place:'river'} },
  { who: 'any', text: "The river's high today, or my boots are short.", when: {place:'river'} },
  { who: 'man', text: "Reeds, ripples, and a very rude heron.", when: {place:'river'} },
  { who: 'woman', text: "Watch the current. It likes to steal things.", when: {place:'river'} },
  { who: 'any', text: "That water is older than the valley. Show some respect.", when: {place:'river'} },
  { who: 'any', text: "I'd fish here all day. The fish disagree.", when: {place:'river'} },
  { who: 'man', text: "Count the sheep? I always lose count at seven.", when: {place:'pasture'} },
  { who: 'woman', text: "Baa. That's all they ever say. Wise creatures.", when: {place:'pasture'} },
  { who: 'any', text: "A sheep got out again. They're escape artists.", when: {place:'pasture'} },
  { who: 'any', text: "The fence is fine. The sheep are smarter than the fence.", when: {place:'pasture'} },
  { who: 'man', text: "Grass, grass, grass. Look at those lucky sheep.", when: {place:'pasture'} },
  { who: 'woman', text: "Good wool this year. Soft as a rumour.", when: {place:'pasture'} },
  { who: 'any', text: "Sheep never hurry. They know something we don't.", when: {place:'pasture'} },
  { who: 'any', text: "Easy work, they say. They've never carried a ram.", when: {place:'pasture'} },
  { who: 'man', text: "This pasture has the best view in Takamori. Ask any sheep.", when: {place:'pasture'} },
  { who: 'woman', text: "The wheel turns, the flour falls. Simple and good.", when: {place:'mill'} },
  { who: 'any', text: "Mind your sleeves near the gears. They're hungry.", when: {place:'mill'} },
  { who: 'any', text: "The mill's been grinding since my grandfather's time.", when: {place:'mill'} },
  { who: 'man', text: "Flour dust makes everyone look wise. Or ghostly.", when: {place:'mill'} },
  { who: 'woman', text: "That wheel is slow, but it never stops.", when: {place:'mill'} },
  { who: 'any', text: "Smell that? Fresh-ground flour. The best perfume.", when: {place:'mill'} },
  { who: 'any', text: "Creak, thump, creak. The best lullaby in the valley.", when: {place:'mill'} },
  { who: 'man', text: "Don't shout at the mill. It shouts back.", when: {place:'mill'} },
  { who: 'woman', text: "It's so quiet since the train stopped. You get used to it.", when: {chapter:[0,1]} },
  { who: 'any', text: "The lamps are dark again. We tell ourselves it's fine.", when: {chapter:[0,1]} },
  { who: 'any', text: "I haven't heard a whistle in years. I still listen.", when: {chapter:[0,1]} },
  { who: 'man', text: "Not many left to say hello to. Thanks for stopping.", when: {chapter:[0,1]} },
  { who: 'woman', text: "Takamori's quiet and Kawabe's quieter. We wave across.", when: {chapter:[0,1]} },
  { who: 'any', text: "I keep the porch light on. Habit. Hope. Mostly habit.", when: {chapter:[0,1]} },
  { who: 'any', text: "Rust on the rails, moss on the sign. Time is patient.", when: {chapter:[0,1]} },
  { who: 'man', text: "Young faces are rare here now. Stay a while.", when: {chapter:[0,1]} },
  { who: 'woman', text: "The valley is asleep. Someone should wake it kindly.", when: {chapter:[0,1]} },
  { who: 'any', text: "Dark lamps, still nights. You can hear your own thoughts.", when: {chapter:[0,1]} },
  { who: 'any', text: "People used to ride end to end just for fun.", when: {chapter:[0,1]} },
  { who: 'man', text: "Ten winters now. I count them, too.", when: {chapter:[0,1]}, story: 'classic' },
  { who: 'man', text: "Star Festival this winter. I'm counting the sleeps.", when: {chapter:[0,1]}, story: 'grandma' },
  { who: 'woman', text: "Once you couldn't hear yourself over the train.", when: {chapter:[0,1]} },
  { who: 'any', text: "A new face! The valley notices, you know.", when: {chapter:[0,1]} },
  { who: 'any', text: "I used to wave at the evening train. Old habits.", when: {chapter:[0,1]} },
  { who: 'man', text: "Did you see that glow? Haven't seen that in years.", when: {chapter:[2,3]} },
  { who: 'woman', text: "My cousin's coming back from the city next month!", when: {chapter:[2,3]} },
  { who: 'any', text: "The lamps are waking up. Slowly, like us in the morning.", when: {chapter:[2,3]} },
  { who: 'any', text: "More windows are lit every week. I count them.", when: {chapter:[2,3]} },
  { who: 'man', text: "People are moving home. Somebody has to bake for them.", when: {chapter:[2,3]} },
  { who: 'woman', text: "I swept the porch. Somebody might visit, now.", when: {chapter:[2,3]} },
  { who: 'any', text: "I heard laughter on the road today. Out loud!", when: {chapter:[2,3]} },
  { who: 'any', text: "There's talk of a festival again. Talk is a start.", when: {chapter:[2,3]} },
  { who: 'man', text: "A light on the hill, a light on the water. Pretty.", when: {chapter:[2,3]} },
  { who: 'woman', text: "My neighbour's back! Now we can argue over the fence.", when: {chapter:[2,3]} },
  { who: 'any', text: "The valley is yawning. It'll be up and about soon.", when: {chapter:[2,3]} },
  { who: 'any', text: "Kids on the lanes again. Noise has never sounded so good.", when: {chapter:[2,3]} },
  { who: 'man', text: "I fixed the shutters. Felt like it was time.", when: {chapter:[2,3]} },
  { who: 'woman', text: "Smoke from a new chimney! I nearly cheered.", when: {chapter:[2,3]} },
  { who: 'any', text: "Four lamps! I never thought I'd see all four.", when: {chapter:[4,5]} },
  { who: 'any', text: "I can't stop looking at that little red engine.", when: {chapter:[4,5]} },
  { who: 'man', text: "The lamps say clear, the sky says clear. Perfect.", when: {chapter:[4,5]} },
  { who: 'woman', text: "Takamori and Kawabe, one valley again. About time.", when: {chapter:[4,5]}, story: 'classic' },
  { who: 'woman', text: "Both villages on one platform! Sora's doing, I bet.", when: {chapter:[4,5]}, story: 'grandma' },
  { who: 'any', text: "Lanterns everywhere. Mind your hat.", when: {chapter:[4,5]} },
  { who: 'any', text: "I made a wish list for star-fall. It's very long.", when: {chapter:[4,5]} },
  { who: 'man', text: "Everybody's smiling. It's a little suspicious.", when: {chapter:[4,5]} },
  { who: 'woman', text: "We waited ten winters. What's another ten minutes?", when: {chapter:[4,5]}, story: 'classic' },
  { who: 'woman', text: "We waited all year. What's another ten minutes?", when: {chapter:[4,5]}, story: 'grandma' },
  { who: 'any', text: "The valley hums again. I can feel it in my boots.", when: {chapter:[4,5]} },
  { who: 'any', text: "Star-fall and four lamps. I could get used to this.", when: {chapter:[4,5]} },
  { who: 'man', text: "Wear something warm and silly. That's the dress code.", when: {chapter:[4,5]} },
  { who: 'woman', text: "Even the sheep look pleased with themselves.", when: {chapter:[4,5]} },
  { who: 'any', text: "Somebody hung a lantern on my gate. I'm keeping it.", when: {chapter:[4,5]} },
  { who: 'any', text: "Tonight the whole valley is awake. Even the cat.", when: {chapter:[4,5]} },
  { who: 'kid', text: "I can run faster than the ferry! Sort of.", when: {} },
  { who: 'kid', text: "Look, I found a stick. It's a very good stick.", when: {} },
  { who: 'kid', text: "I'm not hiding. I'm winning at hide-and-seek.", when: {} },
  { who: 'kid', text: "My shoe has a hole. Now my toes can see, too.", when: {} },
  { who: 'kid', text: "Teacher says stars are far away. I say not that far.", when: {} },
  { who: 'kid', text: "Race you to the bridge! Ready, go! Too slow!", when: {} },
  { who: 'kid', text: "One day I'll ride a bicycle. A really tall one.", when: {} },
  { who: 'kid', text: "Mum says no more puddles. This is a pond. Different.", when: {} },
  { who: 'kid', text: "I have a pebble that looks like a cat. Wanna see?", when: {} },
  { who: 'kid', text: "I'm not tired. I'm just lying down very fast.", when: {} },
  { who: 'kid', text: "I'm the king of this wall. Bow down. Or wave.", when: {} },
  { who: 'kid', text: "I counted three clouds shaped like dumplings.", when: {} },
  { who: 'kid', text: "Do bears like bread? Asking for a friend.", when: {} },
  { who: 'kid', text: "I fed the ducks a little. A little a lot.", when: {} },
  { who: 'kid', text: "I'm gonna catch the biggest fish ever. Maybe next week.", when: {} },
  { who: 'kid', text: "My kite got stuck. Tell it I said sorry.", when: {} },
  { who: 'kid', text: "Shh! I'm being a spy. Spy things.", when: {} },
  { who: 'kid', text: "Granny says the lamps used to shine like the moon.", when: {} },
  { who: 'kid', text: "I know a secret path. It's behind the big bush.", when: {} },
  { who: 'kid', text: "Can I have a bun? I'll be good. Fifty percent good.", when: {} },
  { who: 'kid', text: "Look at me, I'm doing a cartwheel! Don't look!", when: {} },
  { who: 'kid', text: "I'm the third fastest in school. Out of four.", when: {} },
  { who: 'kid', text: "My tooth wobbles! It's my best trick.", when: {} },
  { who: 'any', text: "In my day we walked uphill both ways. Twice.", when: {} },
  { who: 'any', text: "Ah, young legs. Take them for a good long walk.", when: {} },
  { who: 'any', text: "I remember when this lane was all mud. It still is.", when: {} },
  { who: 'any', text: "Come by for tea, dear. I'll find the good cups.", when: {} },
  { who: 'any', text: "My husband always said the valley hums. He was right.", when: {} },
  { who: 'any', text: "Bread used to cost a smile. Now it costs two.", when: {} },
  { who: 'any', text: "Mind your back, child, and mind your manners.", when: {} },
  { who: 'any', text: "My grandmother said stars fall into the river here.", when: {} },
  { who: 'any', text: "Sit a while! The bench has room and so do I.", when: {} },
  { who: 'any', text: "At my age, a quiet hour is a feast.", when: {} },
  { who: 'man', text: "Hello, traveller! Welcome to the valley.", when: {} },
  { who: 'woman', text: "Ho there! Come and say hi. We don't bite.", when: {} },
  { who: 'any', text: "Hi! Don't mind us, we're just being neighbourly.", when: {} },
  { who: 'any', text: "Good day! Spare a smile? I'm collecting them.", when: {} },
  { who: 'man', text: "Oh, hello! Is that a new coat, or just a good one?", when: {} },
  { who: 'woman', text: "Hey there! You walk like someone with plans.", when: {} },
  { who: 'any', text: "Hullo! Free advice: eat something warm.", when: {} },
  { who: 'any', text: "Welcome, welcome! Take any path. They all end at tea.", when: {} },
  { who: 'man', text: "Hi, hi! Tell your feet I said well done.", when: {} },
  { who: 'woman', text: "Ahoy! That's how they say hello by the river, I think.", when: {} },
  { who: 'any', text: "Evening! Lantern oil is half price.", when: {night:true} },
  { who: 'any', text: "Morning! The bread's still warm, if you're quick.", when: {night:false} },
  { who: 'genzo', text: "Mind the platform edge. I'm not mopping you up.", when: {} },
  { who: 'genzo', text: "Brass doesn't polish itself. I checked.", when: {} },
  { who: 'genzo', text: "Humph. Don't loiter. Or do. I'm not your boss.", when: {} },
  { who: 'genzo', text: "My knees forecast the weather. Today: grumpy.", when: {} },
  { who: 'genzo', text: "Good boots. Keep them.", when: {} },
  { who: 'genzo', text: "Back when I was young, a ticket meant something.", when: {} },
  { who: 'genzo', text: "Tea's gone cold. Forgot to drink it. Again.", when: {} },
  { who: 'genzo', text: "I whistle when nobody's listening. Keep that quiet.", when: {} },
  { who: 'genzo', text: "Frost on the rails. Pretty. Hard on the knees.", when: {season:'winter'} },
  { who: 'genzo', text: "Late to be walking. Wrap up warm.", when: {night:true} },
  { who: 'genzo', text: "Hot enough to fry an egg on the signal box.", when: {season:'summer'} },
  { who: 'rin', text: "Catch of the day! Well, catch of the hour. Okay, minute.", when: {} },
  { who: 'rin', text: "Race you to the dock! I'll give you a head start.", when: {} },
  { who: 'rin', text: "The river told me a joke. I forgot the end.", when: {} },
  { who: 'rin', text: "Bait's in my pocket. Don't ask. Don't look.", when: {} },
  { who: 'rin', text: "Biggest fish ever! Well, bigger than yesterday's.", when: {} },
  { who: 'rin', text: "Come fishing sometime! There are almost no rules.", when: {} },
  { who: 'rin', text: "After dark the river's all stars. Fish wink at them.", when: {night:true} },
  { who: 'rin', text: "Swim, fish, swim again. That's my whole summer!", when: {season:'summer'} },
  { who: 'ota', text: "Mm.", when: {} },
  { who: 'ota', text: "Turnips. Always turnips.", when: {} },
  { who: 'ota', text: "Wheel's turning. Good.", when: {} },
  { who: 'ota', text: "Flour in the air. Ignore it.", when: {} },
  { who: 'ota', text: "Weeds. Always weeds.", when: {} },
  { who: 'ota', text: "Walk on. Nothing to see here.", when: {} },
  { who: 'ota', text: "Mind the wheel. It bites.", when: {} },
  { who: 'ota', text: "Fine day for work. Every day is.", when: {} },
  { who: 'ota', text: "Harvest. No talking.", when: {season:'autumn'} },
  { who: 'ota', text: "Cold. Fire. Soup. Enough.", when: {season:'winter'} },
  { who: 'ota', text: "Late. Go to bed.", when: {night:true} },
  { who: 'hana', text: "Warm bun? Half price if you smile!", when: {} },
  { who: 'hana', text: "Hello, love! I've got more flour than sense.", when: {} },
  { who: 'hana', text: "Eat something, love. You look like you're overthinking.", when: {} },
  { who: 'hana', text: "The oven's singing again. That means it's ready!", when: {} },
  { who: 'hana', text: "A bun a day keeps the grumps away.", when: {} },
  { who: 'hana', text: "Cinnamon, peaches, a little luck. Come and have one!", when: {} },
  { who: 'hana', text: "First batch is out! Quick, before they're gone!", when: {night:false} },
  { who: 'hana', text: "Hot buns for cold hands, love.", when: {season:'winter'} },
  { who: 'hana', text: "Peach blossom buns today. Pretty and sweet!", when: {season:'spring'} },
];
